### ISSUE TITLE
Set up QA process for lemmatizer

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/utils#18]
DoD:
- implement metric from PolEval to calculate lemmatization accuracy
- add the process that takes the lemmatizer and a dataset and calculates its accuracy
- save the metric so that DVC allows us to make experimens and compare the metric between branches (read DVC documentation related to metrics first)

**Comment by MateuszOlko** [comment]
@Gizzio  Please leave a comment when you tag something as blocked :)

**Comment by Gizzio** [comment]
@MateuszOlko i need you to rebase lemmatizer to master, and resolve conflicts (consult with @DoomCoder ). Polish lang class is unloadable. Ping me when it's done.

**Comment by Gizzio** [comment]
@MateuszOlko need help again, details on slack.

**Comment by kowaalczyk** [comment]
https://github.com/spacy-pl/utils/tree/feature/lemmatizer-eval%2318

**Comment by kowaalczyk** [comment]
New scope: just check the rules that are implemented (only on correct POS tags)

There will be no way of checking how well the script works, until the PR is merged and models will be able to use new tagmap early enough,
