### ISSUE TITLE
Fix tagmap generation:

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/utils#38]
Fix bugs & incompatibility with python 2.7:
- [x] remove "features" field - causes error
- [x] add ''' # coding: utf8 from __future__ import unicode_literals '''
- [x] refactor generated code
- [x] change generated file name to tag_map.py
- [x] add latest version of polish tagmap in spacy:master to dvc
- [x] make script merge our tagmap with latest tagmap from spacy:master (added above)

**Comment by DoomCoder** [comment]
@Gizzio review please

**Comment by MateuszOlko** [comment]
@Gizzio takeover
