### ISSUE TITLE
NER Wrocław

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/utils#39]
DoD:
- loaded dataset
- trained NER model
- if the dataset is not good enough, explain in comments and don't waste time on training

**Comment by DoomCoder** [comment]
https://github.com/spacy-pl/utils/pull/44

**Comment by DoomCoder** [comment]
@Gizzio please review

**Comment by Gizzio** [comment]
@DoomCoder pls remember to ping me when you solve rebase issues

**Comment by DoomCoder** [comment]
@Gizzio done
