### ISSUE TITLE
Convert NER to spaCy format

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/utils#5]
Source data: http://clip.ipipan.waw.pl/NationalCorpusOfPolish

DoD:

* NER data converted to spacy json format, ready to be loaded for model training

**Comment by MateuszOlko** [comment]
@DoomCoder Zapomniałes dodać pokorpus milionowy do dvc. Nie da się zreprodukować pipelinu

**Comment by DoomCoder** [comment]
https://github.com/spacy-pl/utils/pull/40
