### ISSUE TITLE
Prepare storage for models

### ISSUE THREAD

**Issue by MateuszOlko** [spacy-pl/utils#56]
DoD:
- [x] Storage for models from Sigmo (PUBLICLY AVAILABLE)
- [x] Script for uploading models to bucket
- [x] Latest model packed and uploaded to bucket

**Comment by Gizzio** [comment]
@kowaalczyk task ublocked

**Comment by kowaalczyk** [comment]
@tomekkorbak Jestem w stanie wyświetlić zawartość bucketa przy użyciu gsutil ale nie mam dostępu do dodawania do niego plików:
```
ResumableUploadAbortException: 403 spacypl@starry-battery-103809.iam.gserviceaccount.com does not have storage.objects.create access to spacy-pl-public-models.
```

**Comment by tomekkorbak** [comment]
Oki, spojrzę na to!
