### ISSUE TITLE
Fix tag map

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/utils#9]
DoD:

- [x] tag set conversion, tag map generation on 1 branch
- [x] scripts moved from analysis to a separate folder (such as tag_conversion or sth)
- [x] data stored in separate, well-named folder(s)
- [x] fix the bug in generating mapping old tag -> new tag (when tag A is merged to B and B to C, the relation A->C is currently lost)
- [x] add options  to the script: output file path, minimal tagset cardinality

**Comment by MateuszOlko** [comment]
PR opened #10
